# -*- coding: utf-8 -*-
"""cis556_data_transform.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M8lRNBlIYMbem0HrX9ChQD1fMnEYidxp
"""

import pandas as pd
import numpy as np

"""# metro median price df"""

df1 = pd.read_csv('./metro_median_price.csv')

df1

df1.columns = df1.columns.str.replace('-','_')

df1.columns[5:]

df1.columns = ['date_'+str(col)
                if col in df1.columns[5:]
                else col for col in df1.columns]

df1

columns = []
for i in df1.columns:
    print(i+',')
    columns.append(i)

columns

# df1 = df1.add_prefix('date_')

df1.to_csv('./metro_median_price_tranformed.csv')

"""# metro median sale df"""

df2 = pd.read_csv('./metro_median_sale.csv')

df2

df2.columns = df2.columns.str.replace('-','_')

df2.columns[5:]

df2.columns = ['date_'+str(col)
                if col in df2.columns[5:]
                else col for col in df2.columns]

df2

columns[:-1]

df2 = df2[columns[:-1]]

df2

df2.to_csv('./metro_median_sale_transformed.csv')

"""# metro listing cut df"""

df3 = pd.read_csv('./metro_share_listings_price_cut.csv')

df3

df3.columns = df3.columns.str.replace('-','_')

df3.columns[5:]

df3.columns = ['date_'+str(col)
                if col in df3.columns[5:]
                else col for col in df3.columns]

df3

df3.to_csv('./metro_share_listings_price_cut_transformed.csv')

"""# metro zori df"""

df4 = pd.read_csv('./metro_zori.csv')

df4

df4.columns = df4.columns.str.replace('-','_')

df4.columns[5:]

df4.columns = ['date_'+str(col)
                if col in df4.columns[5:]
                else col for col in df4.columns]

df4 = df4[columns]

df4

df4.to_csv('./metro_zori_transformed.csv')

